server {
    listen 80;
    server_name localhost;

    # Frontend estatico
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Proxy reverso a microservicios
    location /api/products {
        # GET - Consultar productos
        if ($request_method = GET) {
            proxy_pass http://get-products:3001;
        }
        # POST - Crear producto
        if ($request_method = POST) {
            proxy_pass http://create-product:3002;
        }
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # PUT y DELETE requieren capturar el ID
    location ~ ^/api/products/(\d+)$ {
        # PUT - Modificar producto
        if ($request_method = PUT) {
            proxy_pass http://update-product:3003;
        }
        # DELETE - Eliminar producto
        if ($request_method = DELETE) {
            proxy_pass http://delete-product:3004;
        }
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

# 2026 - Disenador asignatura: Ignacio A. Pastenet M.
