resolver 127.0.0.11 valid=10s;

map $request_method $api_backend_collection {
    GET    http://get-products:3001;
    POST   http://create-product:3002;
}

map $request_method $api_backend_item {
    PUT    http://update-product:3003;
    DELETE http://delete-product:3004;
}

server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
        
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
        add_header Pragma "no-cache";
        add_header Expires "0";
    }

    location /api/products {
        proxy_pass $api_backend_collection;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location ~ ^/api/products/(\d+)$ {
        proxy_pass $api_backend_item;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}