# ============================================
# EscolarOnline - Docker Compose (AWS EC2)
# Actividad 1.6 - Arquitectura Cloud ARY1102
# ============================================
# Uso en EC2: docker compose -f docker-compose.aws.yml up -d
# Nota: Reemplazar <ACCOUNT_ID> y <REGION> con valores reales
# Nota: Reemplazar <DB_HOST> con IP privada del EC2 MySQL

services:
  # Frontend (Nginx + HTML/CSS/JS)
  frontend:
    image: <ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/escolaronline-frontend:latest
    container_name: escolaronline-frontend
    ports:
      - "80:80"
    depends_on:
      - get-products
      - create-product
      - update-product
      - delete-product
    networks:
      - escolaronline-net

  # Microservicio: Consultar productos (GET)
  get-products:
    image: <ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/escolaronline-get-products:latest
    container_name: escolaronline-get-products
    ports:
      - "3001:3001"
    environment:
      DB_HOST: <DB_HOST>
      DB_USER: alumno
      DB_PASS: alumno123
      DB_NAME: escolar_online
      DB_PORT: 3306
      PORT: 3001
    networks:
      - escolaronline-net

  # Microservicio: Crear producto (POST)
  create-product:
    image: <ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/escolaronline-create-product:latest
    container_name: escolaronline-create-product
    ports:
      - "3002:3002"
    environment:
      DB_HOST: <DB_HOST>
      DB_USER: alumno
      DB_PASS: alumno123
      DB_NAME: escolar_online
      DB_PORT: 3306
      PORT: 3002
    networks:
      - escolaronline-net

  # Microservicio: Modificar producto (PUT)
  update-product:
    image: <ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/escolaronline-update-product:latest
    container_name: escolaronline-update-product
    ports:
      - "3003:3003"
    environment:
      DB_HOST: <DB_HOST>
      DB_USER: alumno
      DB_PASS: alumno123
      DB_NAME: escolar_online
      DB_PORT: 3306
      PORT: 3003
    networks:
      - escolaronline-net

  # Microservicio: Eliminar producto (DELETE)
  delete-product:
    image: <ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/escolaronline-delete-product:latest
    container_name: escolaronline-delete-product
    ports:
      - "3004:3004"
    environment:
      DB_HOST: <DB_HOST>
      DB_USER: alumno
      DB_PASS: alumno123
      DB_NAME: escolar_online
      DB_PORT: 3306
      PORT: 3004
    networks:
      - escolaronline-net

networks:
  escolaronline-net:
    driver: bridge

# 2026 - Disenador asignatura: Ignacio A. Pastenet M.
